#!/usr/bin/env bash
shopt -s globstar
javac -d out -cp "lib/snmpv3/*:lib/outline/*" src/**/*.java &&
java -p out -cp "out:lib/snmpv3/*:lib/outline/*" \
	-Dsun.java2d.uiScale=$(grep -Po '(?<=<scale>)[0-9.]+' ~/.config/monitors.xml) \
	rs.ac.bg.etf.rm2.dk140414d.projekat.Main
